name: Expose Kubernetes Service on AWS
"on":
  push:
    branches:
      - main
jobs:
  expose_service:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install kubectl
        run: >
          curl -LO "https://dl.k8s.io/release/$(curl -L -s
          https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"

          chmod +x kubectl

          sudo mv kubectl /usr/local/bin/
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
          aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          aws-session-token: "${{ secrets.AWS_SESSION_TOKEN }}"
          aws-region: "${{ secrets.AWS_REGION }}"

      - name: Connect to EKS Cluster
        run: |
          aws eks update-kubeconfig --name cluster-postech-challenge-3  --region ${{ secrets.AWS_REGION }}
      - name: Apply Load Balancer Configuration
        run: |
          kubectl apply -f apps/private-lb.yml -n postech & \
          kubectl apply -f apps/public-lb.yml -n postech & \
          kubectl apply -f apps/deployment.yml -n postech & \
          kubectl apply -f apps/auto-scaler.yml -n postech
